@startuml encryption-topology

!define AzurePuml https://raw.githubusercontent.com/RicardoNiepel/Azure-PlantUML/release/2-1/dist
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/Identity/AzureActiveDirectory.puml
!includeurl AzurePuml/Security/AzureKeyVault.puml
!includeurl AzurePuml/Security/AzureSentinel.puml
!includeurl AzurePuml/Management/AzureLogAnalytics.puml
!includeurl AzurePuml/Management/AzureMonitor.puml
!includeurl AzurePuml/DevOps/AzureApplicationInsights.puml
!includeurl AzurePuml/Compute/AzureFunction.puml
!includeurl AzurePuml/Compute/AzureVirtualMachine.puml
!includeurl AzurePuml/Compute/AzureVirtualMachineScaleSet.puml
!includeurl AzurePuml/Analytics/AzureEventHub.puml
!includeurl AzurePuml/Analytics/AzureDatabricks.puml
!includeurl AzurePuml/Analytics/AzureAnalysisServices.puml
!includeurl AzurePuml/Databases/AzureDataFactory.puml
!includeurl AzurePuml/Databases/AzureCosmosDb.puml
!includeurl AzurePuml/Databases/AzureSqlDatabase.puml
!includeurl AzurePuml/Databases/AzureSqlDataWarehouse.puml
!includeurl AzurePuml/Storage/AzureBlobStorage.puml
!includeurl AzurePuml/Storage/AzureDataLakeStorage.puml
!includeurl AzurePuml/Management/AzurePolicy.puml
!includeurl AzurePuml/Networking/AzureVirtualNetwork.puml
!includeurl AzurePuml/Networking/AzureExpressRoute.puml
!includeurl AzurePuml/Networking/AzureVPNGateway.puml
!includeurl AzurePuml/Web/AzureWebApp.puml

LAYOUT_LEFT_RIGHT

' title Azure Operational Topology (single-region)

skinparam BackgroundColor #002b36
skinparam TitleFontColor #eee8d5
skinparam TitleFontSize 35

skinparam Rectangle {
    BackgroundColor<<functionalGroup>> #586e75
    FontColor<<functionalGroup>> #eee8d5
    FontSize<<functionalGroup>> 36
    BackgroundColor<<AzureVirtualMachineScaleSet>> #CCFFDD
}

skinparam package<<container>> {
    StereotypeFontColor<<VirtualNetworks>> #eee8d5
    FontSize 16
}

skinparam ArrowThickness 4
skinparam ArrowFontSize 22

Rectangle "On-Premises" <<functionalGroup>> {
    Container(dataFile, "Source system", "SSN,RX_ID, SERVICE_DATE")
    AzureVirtualMachine(console, "INGEST", "Always Protected SDK", "Service Principal")
}

Rectangle "Encryption Infrastructure" <<functionalGroup>> {
    AzureKeyVault(kvphi, "PHI vault", "Premium SKU for HSM", "RBAC for CMKs\nSoft delete\nPurge protection\nResource locking")
    AzureBlobStorage(keymetadata, "Encryption Metadata", "General Purpose V2 (RA-GRS)", "WORM-backed storage\nGeo-replicated\nVersioning")
}

Rectangle "Data Engines" <<functionalGroup>> {
    AzureDataFactory(adf, "Data Orchestration", "Data import and processing definitions")
    AzureDataLakeStorage(adls, "STORE", "Gen2 w/AAD-based RBAC", "Parquet files w/ embedded key metadata")
    AzureDatabricks(databricks, "PREPARE", "Parquet Modular Encryption","Service Principal") {
        Container(azureSdk, "Azure SDK", "Cosmos DB client", "")
        Container(udf, "User Defined Function", "MDE SDK", "Avro file support")
    }

    AzureCosmosDb(cosmos, "Transactions", "Always Encrypted\nChange Feed", "CMK metadata\nCEK metadata")
    AzureSqlDatabase(sql, "OLTP / Reporting", "SQL Always Encrypted", "CMK metadata\nCEK metadata")
}

Rectangle "Processing" <<functionalGroup>> {
    AzureFunction(changeFeedFunc, "PROCESS", "App Services / Container", "Managed Identity") {
        Container(cosmosDbSdk, "Cosmos SDK", "", "")
    }

    AzureVirtualMachine(sqlClientVM, "QUERY", "", "") {
        Container(sqlDriver, "SQL Client", "", "")
    }
}

Rectangle "Event Streaming" <<functionalGroup>> as EventStream {
    AzureEventHub(eventhub, "Events", "Standard or Kafka", "Includes FLE-protected columns (Avro)")
    AzureFunction(function, "INGEST", "App Services / Container", "Managed Identity")
}

eventhub -[#eee8d5]-> function: "<color:#eee8d5>Event trigger"
function <-[#cb4b16]--- keymetadata
function -[#859900]---> kvphi
function -[#eee8d5]-> function: "<color:#eee8d5>Decrypt, process"

console -[#859900]-> kvphi: "<color:#859900>UNWRAP DEK"

dataFile -[#eee8d5]-> console: "<color:#eee8d5>Data Factory connector"
console <-[#cb4b16]- keymetadata: "<color:#cb4b16>LOAD CONFIG"
console -[#eee8d5]-> console: "<color:#eee8d5>Encrypt: SSN, PAT_ID with DEK"
console -[#eee8d5]-> adls: "<color:#eee8d5>Push FLE-protected data"

adf -[#eee8d5]-> databricks
adls -[#eee8d5]-> databricks: "<color:#eee8d5>Load raw data"
udf -[#859900]-> kvphi
udf -[#002b36]-> udf: "<color:#002b36>Decrypt, process, encrypt"
udf -[#002b36]-> azureSdk

azureSdk -[#268bd2]-> sql: "<color:#eee8d5>Push data w/ FLE"
azureSdk -[#268bd2]-> cosmos: "<color:#eee8d5>Push data w/ FLE"

cosmos -[#eee8d5]--> cosmosDbSdk: "<color:#eee8d5>Changes"
kvphi <-[#859900]- cosmosDbSdk
cosmosDbSdk -[#002b36]-> cosmosDbSdk: "<color:#002b36>Decrypt"

sql <--[#eee8d5]- sqlDriver: "<color:#eee8d5>Query"
kvphi <-[#859900]- sqlDriver
sqlDriver -[#002b36]-> sqlDriver: "<color:#002b36>Decrypt"

@enduml